# Nama Aplikasi
spring.application.name=catalog-service

# Port server
server.port=8081

# Konfigurasi Koneksi PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi JPA / Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update